### ISSUE TITLE
RLBench ActionMode attribute action_size not found

### ISSUE THREAD

**Issue by mirkomorati** [tensorlayer/RLzoo#12]
I was trying to use the RLzoo algorithms for the RLBench environment and I got an error from line 50 in the [`build_rlbench_env.py`](https://github.com/tensorlayer/RLzoo/blob/7bf53efc1d83219fb77849384e50e1cee5124431/rlzoo/common/build_rlbench_env.py#L50) file.

Seems like in [this commit](https://github.com/stepjam/RLBench/commit/886fc11ba0ee869f98aa132b143b0a9126837862#diff-5e68ba1f578720f5ba6b342a524bf08a) they replaced where to get the `action_size` attribute, now line 50 should be

` self.action_space =  spaces.Box(low=-1.0, high=1.0, shape=(self.env.action_size,), dtype=np.float32)`

**Comment by quantumiracle** [comment]
Hi,

Thanks for pointing out that! I've merged the request.

Best regards,
Zihan
