### ISSUE TITLE
How to properly introduce a new RLBench task?

### ISSUE THREAD

**Issue by Atlis** [tensorlayer/RLzoo#21]
Hello!

I want to introduce a new RLBench task (or also override one). How do I accomplish this properly? The only way I can think of now is to rewrite parts of the code in the RLBench package, which I don't think is the proper way to do it. Should there be an argument to indicate where the task is defined?

Thank you!

**Comment by quantumiracle** [comment]
Hi, 
Are you planning to simply create a new task in RLBench or also learning the new task with RLzoo? For the first case, you may refer to the original [RLBench website](https://github.com/stepjam/RLBench) to see how to create a new task without modifying its code. For the second case where you also need to apply RLzoo for the new task, you will need to register the new environment in RLBench and add the name [here](https://github.com/tensorlayer/RLzoo/blob/a4d910c0f5febbf568e4cfd4985e0f94fd4c38c9/rlzoo/common/env_list.py#L800) in RLzoo `common/env_list.py.`

**Comment by Atlis** [comment]
It was for the second case. I will try that! Thank you!

**Comment by Atlis** [comment]
Beside all this, I decided to reinstall RLBench and RLzoo packages with `pip install -e <path to package>` so that I can edit the code directly in my development folder.
