### ISSUE TITLE
dqn.py exploration rate is wrong

### ISSUE THREAD

**Issue by yjxaigithub** [tensorlayer/RLzoo#26]
https://github.com/tensorlayer/RLzoo/blob/master/rlzoo/algorithms/dqn/dqn.py#L178-L179
should be modified to  "eps = 1 - (1 - exploration_final_eps) * min(1, i / (exploration_rate * train_episodes * max_steps))"

**Comment by quantumiracle** [comment]
Thanks for pointing out. I think what you said is correct. I've modified it.
