### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by yjxaigithub** [tensorlayer/RLzoo#29]
When I run the run_dqn.py with setting QNetwork(...)'s parameter state_only=False,  "states, actions = inputs" in value_networks.py occurrs a ValueError  as the title indicates. It occurs because "obv = np.expand_dims(obv, 0).astype('float32')"  in dqn.py. I think if state_only = False, obv should add act_inputs for debugging. Hope you can fix this error.

**Comment by quantumiracle** [comment]
I think the error you got means you are not sending actions to the value network but set `state_only = False`. When setting `state_only = False`, you should ensure that there are additional action inputs. See [here](https://github.com/tensorlayer/RLzoo/blob/c817aadee3f249139aac599b53ac6109abc862e6/rlzoo/common/value_networks.py#L208).
