### ISSUE TITLE
A suggestion about kl divergence and entropy implementation of categorical distribution

### ISSUE THREAD

**Issue by yjxaigithub** [tensorlayer/RLzoo#31]
In https://github.com/tensorlayer/RLzoo/blob/master/rlzoo/common/distributions.py#L99, I think there is a concise implementation：

```python
@expand_dims
def kl(self, logits):
    p = tf.exp(self._logits)
    kl = tf.reduce_sum(p * (self._logits-logits), axis=-1)
    return kl
```
Similarly in https://github.com/tensorlayer/RLzoo/blob/master/rlzoo/common/distributions.py#L115

```python
@expand_dims
def entropy(_logits):
    p = tf.exp(_logits)
    return tf.reduce_sum(-p * _logits, axis=-1)
```
I don’t know the reason why you implemented it in a more complicated way in your code. Is it convenient to tell me?

**Comment by quantumiracle** [comment]
Thanks. This is also solved as in #32.
