### ISSUE TITLE
How to install it with pip?

### ISSUE THREAD

**Issue by zkx741481546** [tensorlayer/RLzoo#8]

**Comment by zsdonghao** [comment]
pip install rlzoo

**Comment by zkx741481546** [comment]
> pip install rlzoo

![image](https://user-images.githubusercontent.com/31107435/73717877-f2d41900-4755-11ea-8cbb-50432cd00b39.png)

**Comment by quantumiracle** [comment]
Hi, 
It should be fine now. You can take a try.

**Comment by zkx741481546** [comment]
> Hi,
> It should be fine now. You can take a try.

yes, I can install it now. Thanks
